'use client';
import {useEffect,useMemo,useState} from 'react';
import {InventoryItem,Lane} from '../lib/types';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export default function Home(){
 const [items,setItems]=useState<InventoryItem[]>([]); const [lane,setLane]=useState<'ALL'|Lane>('ALL'); const [showAdd,setShowAdd]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{fetch('/api/inventory',{cache:'no-store'}).then(async r=>{if(r.status===401){location.href='/login';return []}if(!r.ok)throw new Error('Could not load inventory');return r.json()}).then(x=>{if(Array.isArray(x))setItems(x)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const visible=lane==='ALL'?items:items.filter(i=>i.lane===lane);
 const k=useMemo(()=>({ask:items.reduce((a,i)=>a+i.prices.ask,0),target:items.reduce((a,i)=>a+i.prices.target,0),floor:items.reduce((a,i)=>a+i.prices.hardFloor,0),sold:items.reduce((a,i)=>a+(i.sale?.soldPrice||0),0)}),[items]);
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const form=e.currentTarget;const f=new FormData(form);const ask=Number(f.get('ask'))||0,target=Number(f.get('target'))||ask,soft=Number(f.get('soft'))||target,hard=Number(f.get('hard'))||soft;const body={title:String(f.get('title')),lane:String(f.get('lane')) as Lane,category:String(f.get('category')),condition:String(f.get('condition')||'Used'),description:String(f.get('description')||''),prices:{marketValue:ask,ask,target,softFloor:soft,hardFloor:hard}};const r=await fetch('/api/inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.status===401){location.href='/login';return}const data=await r.json();if(!r.ok){setError(data?.detail||data?.error||'Could not save item');return}setItems(v=>[...v,data]);form.reset();setShowAdd(false)}
 return <main><header><div><span className="eyebrow">EMG // MOVE LIQUIDATION</span><h1>Everything Must Go</h1><p>Inventory Brain · Parker, CO · Sell deadline <b>October 25, 2026</b></p></div><button className="primary" onClick={()=>setShowAdd(true)}>+ SELL SOMETHING</button></header>
 <section className="kpis"><K label="LIST VALUE" v={money(k.ask)}/><K label="REALISTIC TARGET" v={money(k.target)}/><K label="HARD FLOOR" v={money(k.floor)}/><K label="CASH COLLECTED" v={money(k.sold)}/><K label="REMAINING" v={String(items.filter(i=>i.status!=='SOLD').length)}/></section>
 <nav>{(['ALL','HOUSEHOLD','CARD','FLIP'] as const).map(x=><button className={lane===x?'active':''} onClick={()=>setLane(x)} key={x}>{x}</button>)}</nav>
 {error&&<section className="guard"><b>EMG NOTICE</b><span>{error}</span></section>}<section className="panel"><div className="panelHead"><div><span className="eyebrow">V2 INVENTORY BRAIN</span><h2>Sales Board</h2></div><span>{loading?'Loading…':`${visible.length} records`}</span></div><div className="table"><div className="row labels"><span>ITEM</span><span>STATUS</span><span>ASK</span><span>TARGET</span><span>FLOOR</span><span>NEXT ACTION</span></div>{visible.map(i=><div className="row" key={i.id}><span><b>{i.title}</b><small>{i.id} · {i.category}</small></span><span><em>{i.status}</em></span><span>{money(i.prices.ask)}</span><span>{money(i.prices.target)}</span><span>{money(i.prices.hardFloor)}</span><span>{i.nextAction}</span></div>)}</div></section>
 <section className="guard"><b>PRICE GUARDRAIL ACTIVE</b><span>EMG will never recommend accepting below an item's HARD FLOOR. Meaningful price/deal decisions remain in NEEDS LOGAN.</span></section>
 {showAdd&&<div className="modal"><form onSubmit={add}><div className="formHead"><div><span className="eyebrow">V3 INTAKE</span><h2>Sell Something</h2></div><button type="button" onClick={()=>setShowAdd(false)}>✕</button></div><label>Item name<input name="title" required/></label><div className="two"><label>Lane<select name="lane"><option>HOUSEHOLD</option><option>CARD</option><option>FLIP</option></select></label><label>Category<input name="category" required/></label></div><label>Condition<input name="condition" placeholder="Used - Good"/></label><label>Description<textarea name="description"/></label><div className="four"><label>Ask<input name="ask" type="number"/></label><label>Target<input name="target" type="number"/></label><label>Soft floor<input name="soft" type="number"/></label><label>Hard floor<input name="hard" type="number"/></label></div><div className="drop">📷 PHOTO INTAKE<div>Photo storage connector is the next persistence step. Records are photo-ready.</div></div><button className="primary wide">ADD TO EMG</button></form></div>}
 </main>}
function K({label,v}:{label:string,v:string}){return <div className="kpi"><span>{label}</span><strong>{v}</strong></div>}