export type Json=string|number|boolean|null|{[key:string]:Json|undefined}|Json[];
export type Lane='HOUSEHOLD'|'CARD'|'FLIP';
export type Status='INTAKE'|'RESEARCH'|'DRAFT'|'NEEDS_LOGAN'|'LISTED'|'OFFER'|'SOLD'|'ARCHIVED';
export type Database={public:{Tables:{
inventory_items:{Row:{id:string;display_id:string;owner_id:string;title:string;lane:Lane;category:string;condition:string;description:string;market_value:number;ask:number;target:number;soft_floor:number;hard_floor:number;status:Status;next_action:string;acquisition_cost:number;listed_at:string|null;created_at:string;updated_at:string;version:number};Insert:Partial<Database['public']['Tables']['inventory_items']['Row']>&{display_id:string;title:string;lane:Lane;category:string;condition:string};Update:Partial<Database['public']['Tables']['inventory_items']['Row']>};
item_photos:{Row:{id:string;inventory_id:string;owner_id:string;storage_path:string;content_type:string;byte_size:number;sort_order:number;is_primary:boolean;created_at:string};Insert:Partial<Database['public']['Tables']['item_photos']['Row']>&{inventory_id:string;storage_path:string;content_type:string;byte_size:number};Update:Partial<Database['public']['Tables']['item_photos']['Row']>};
card_details:{Row:{inventory_id:string;owner_id:string;sport:string|null;player:string|null;year:string|null;set_name:string|null;card_number:string|null;parallel:string|null;rookie:boolean|null;insert_name:string|null;grading_company:string|null;grade:string|null;notes:string|null};Insert:Partial<Database['public']['Tables']['card_details']['Row']>&{inventory_id:string};Update:Partial<Database['public']['Tables']['card_details']['Row']>};
sales:{Row:{id:string;inventory_id:string;owner_id:string;sold_price:number;fees:number;shipping:number;other_costs:number;platform:string|null;buyer_ref:string|null;sold_at:string;created_at:string};Insert:Partial<Database['public']['Tables']['sales']['Row']>&{inventory_id:string;sold_price:number};Update:Partial<Database['public']['Tables']['sales']['Row']>};
audit_events:{Row:{id:string;inventory_id:string|null;owner_id:string;kind:string;summary:string;actor:string;metadata:Json;created_at:string};Insert:Partial<Database['public']['Tables']['audit_events']['Row']>&{kind:string;summary:string;actor:string};Update:Partial<Database['public']['Tables']['audit_events']['Row']>};
approvals:{Row:{id:string;inventory_id:string;owner_id:string;kind:string;payload:Json;status:string;created_at:string;decided_at:string|null};Insert:Partial<Database['public']['Tables']['approvals']['Row']>&{inventory_id:string;kind:string};Update:Partial<Database['public']['Tables']['approvals']['Row']>};
price_history:{Row:{id:string;inventory_id:string;owner_id:string;market_value:number;ask:number;target:number;soft_floor:number;hard_floor:number;reason:string|null;created_at:string};Insert:Partial<Database['public']['Tables']['price_history']['Row']>&{inventory_id:string;market_value:number;ask:number;target:number;soft_floor:number;hard_floor:number};Update:Partial<Database['public']['Tables']['price_history']['Row']>}
};Views:{[_ in never]:never};Functions:{[_ in never]:never};Enums:{emg_lane:Lane;emg_status:Status};CompositeTypes:{[_ in never]:never}}};
